### PR TITLE
update1.5.1 + remove corrupted Parties

### PR DESCRIPTION
**Pull request by Manpapper**
It's just a small fix, I don't know if it will be possible to identity what cause Troop to be created without some crucial information.
For now let's remove them...

### CODE REVIEW

**Comment by Splintertx** [comment]
This is an interesting solution. How did you come up with the age == 0 method to detect corrupted troops?

**Comment by Manpapper** [comment]
I debug the game and check the stats of all the troops.
The flag isInitialized was false and age at 0 for corrupted troops (and some other thing but can't remember)
Since I don't know for sure that isInitialized was false in other circonstancies I only check age

**Comment by Splintertx** [comment]
Alright. I've never been able to actually see the error in my own campaigns, so I'll take your word for it. Thank you for this.

**Comment by Manpapper** [comment]
It's weird for me that you never encountered this since I have it in all my game at some point with this mod

**Comment by Manpapper** [comment]
image
image

**Pull request merged**
